repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^site/
    -   id: end-of-file-fixer
        exclude: ^site/
    -   id: check-yaml
        exclude: ^site/
    -   id: check-added-large-files
        exclude: ^site/
    -   id: check-json
        exclude: ^site/
    -   id: debug-statements
        exclude: ^site/

-   repo: local
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: poetry run black
        language: system
        require_serial: true
        types: [python]
        files: ^src/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^site/

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        description: "MyPy: Optional static typing for Python"
        entry: poetry run mypy
        language: system
        require_serial: true
        types: [python]
        args: [--strict]
        files: ^src/

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
    -   id: markdownlint
        args: [--fix]
        exclude: ^(site/|docs/|data/|README\.md$)

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-gfm
        - mdformat-black
        exclude: ^(site/|docs/|data/|README\.md$)

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
