site_name: OpenAI Model Registry
site_description: A lightweight Python package for validating OpenAI model parameters and capabilities
site_author: Yaniv Golan
site_url: https://yaniv-golan.github.io/openai-model-registry/

repo_name: yaniv-golan/openai-model-registry
repo_url: https://github.com/yaniv-golan/openai-model-registry

theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: ["."]

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_reference.py
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true

nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Getting Started: user-guide/getting-started.md
      - CLI Reference: user-guide/cli.md
      - Model Capabilities: user-guide/model-capabilities.md
      - Parameter Validation: user-guide/parameter-validation.md
      - Advanced Usage: user-guide/advanced-usage.md
      - Testing: user-guide/testing.md
  - API Reference:
      - Overview: api/index.md
      - ModelRegistry: api/model-registry.md
      - ModelCapabilities: api/model-capabilities.md
  - Contributing:
      - Overview: contributing.md
      - Release Process:
          - Overview: contributing/index.md
          - Release Checklist: contributing/RELEASE_CHECKLIST.md
          - Release Workflow: contributing/RELEASE_WORKFLOW.md
      - CLI Maintainers Guide: contributing/cli-maintainers-guide.md
  - Changelog: changelog.md
