name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.0.1'
          virtualenvs-create: true

      - name: Show Poetry version
        run: poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Install ostruct-cli (for pricing tests)
        run: |
          poetry run pip install ostruct-cli==1.6.1

      - name: Lint with ruff
        run: |
          poetry run pip install ruff==0.3.6
          poetry run ruff check . --fix

      - name: Type check with mypy
        run: |
          poetry run mypy

      - name: Test with pytest
        run: |
          poetry run pytest -m "not live and not slow and not flaky"
