name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.0.1'
          virtualenvs-create: true

      - name: Show Poetry version
        run: poetry --version

      - name: Install dependencies
        run: |
          poetry install --extras cli
          poetry run pip install pytest-cov pytest-benchmark

      - name: Ensure pipx is available (for ostruct via pipx)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pipx
          pipx --version

      - name: Run tests with coverage
        env:
          OMR_ALLOW_PIPX: "1"
          OMR_TEST_ALLOW_FAKE: "1"
        run: |
          poetry run pytest --cov=src/openai_model_registry --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
