name: Build and Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/**/*.py'
      - '.github/workflows/docs.yml'

  # Allow manual triggering of the workflow
  workflow_dispatch:

# Add permissions to allow GitHub Pages deployment
permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.0.1'
          virtualenvs-create: true

      - name: Show Poetry version
        run: poetry --version

      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install mkdocs mkdocs-material "mkdocstrings[python]" mkdocs-gen-files

      - name: Generate API reference markdown files
        run: |
          poetry run python docs/gen_reference.py

      - name: Build docs
        run: |
          mkdir -p docs
          # Generate docs from docstrings if they don't exist yet
          if [ ! -f docs/index.md ]; then
            echo "# OpenAI Model Registry" > docs/index.md
            echo "" >> docs/index.md
            echo "Documentation generated from docstrings." >> docs/index.md
          fi
          # Use the existing mkdocs.yml file
          poetry run mkdocs build

          # Verify site directory exists and has content
          ls -la site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true  # Create a fresh gh-pages branch with each deployment
          enable_jekyll: false
