name: Build and Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/**/*.py'
      - '.github/workflows/docs.yml'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true

      - name: Install dependencies
        run: |
          poetry install
          poetry add mkdocs mkdocs-material mkdocstrings[python] mkdocs-gen-files

      - name: Build docs
        run: |
          mkdir -p docs
          # Generate docs from docstrings if they don't exist yet
          if [ ! -f docs/index.md ]; then
            echo "# OpenAI Model Registry" > docs/index.md
            echo "" >> docs/index.md
            echo "Documentation generated from docstrings." >> docs/index.md
          fi
          # Create mkdocs.yml if it doesn't exist
          if [ ! -f mkdocs.yml ]; then
            echo "site_name: OpenAI Model Registry" > mkdocs.yml
            echo "theme: material" >> mkdocs.yml
            echo "plugins:" >> mkdocs.yml
            echo "  - search" >> mkdocs.yml
            echo "  - mkdocstrings:" >> mkdocs.yml
            echo "      handlers:" >> mkdocs.yml
            echo "        python:" >> mkdocs.yml
            echo "          selection:" >> mkdocs.yml
            echo "            docstring_style: google" >> mkdocs.yml
          fi
          poetry run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
