name: Ostruct Pricing Update

on:
  schedule:
    - cron: '0 1 * * 1-6'   # Daily Mon-Sat
    - cron: '0 1 * * 0'     # Weekly Sunday
  workflow_dispatch:

jobs:
  pricing:
    runs-on: ubuntu-latest
    # Strategy/matrix determined dynamically later

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.0.1'
          virtualenvs-create: true

      - name: Show Poetry version
        run: poetry --version

      - name: Install project
        run: |
          poetry install

      - name: Ensure pipx is available (for ostruct via pipx)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pipx
          pipx --version

      - name: Check for API key (guard)
        id: check-secrets
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "skip_fetch=true" >> $GITHUB_OUTPUT
            echo "## Missing OPENAI_API_KEY – skipping ostruct pricing fetch" >> $GITHUB_STEP_SUMMARY
            echo "::warning::OPENAI_API_KEY is not set; skipping pricing fetch steps."
          else
            echo "skip_fetch=false" >> $GITHUB_OUTPUT
          fi

      - name: Quick detector for pricing/model changes
        id: detect
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        if: steps.check-secrets.outputs.skip_fetch != 'true'
        run: |
          TODAY=$(date -u +%F)
          # Build allowed_models and dynamic matrix from data/models.yaml using Python
          poetry run python - <<'PY'
          import json, yaml
          from pathlib import Path
          data = yaml.safe_load(Path('data/models.yaml').read_text())
          models = [k for k,v in (data.get('models') or {}).items() if isinstance(v, dict) and 'pricing' in v and not (v.get('deprecation',{}).get('status')=='deprecated')]
          Path('matrix.json').write_text(json.dumps(models))
          Path('allowed_models.json').write_text(json.dumps(models))
          PY
          ALLOWED_MODELS=$(cat allowed_models.json)
          # Use pipx to run ostruct deterministically
          pipx run --spec ostruct-cli==1.6.1 ostruct run scripts/ostruct/pricing_change_detector.j2 scripts/ostruct/pricing_change_detector_schema.json --enable-tool web-search --tool-choice web-search --ws-context-size low -V today="$TODAY" -J allowed_models="$ALLOWED_MODELS" --model gpt-4.1 --temperature 0 --progress none > detector.json || true
          echo "Detector output:" && cat detector.json || true
          # Decide proceed based on detector schema's proceed flag
          PROCEED=$(jq -r '.proceed // false' detector.json)
          echo "proceed=$PROCEED" >> $GITHUB_OUTPUT
          if [ "$PROCEED" != "true" ]; then
            echo "No actionable changes per detector; downstream fetch will be skipped"
          else
            echo "Detector indicates proceed=true"
          fi

      - name: Set dynamic matrix
        id: set-matrix
        run: |
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

      - name: Fetch pricing via ostruct
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OMR_ALLOW_PIPX: "1"
        if: steps.check-secrets.outputs.skip_fetch != 'true' && steps.detect.outputs.proceed == 'true' && steps.set-matrix.outputs.matrix != ''
        run: |
          echo "Dynamic models:" && cat matrix.json
          for m in $(jq -r '.[]' matrix.json); do
            echo "Fetching pricing for $m"
            poetry run python src/openai_model_registry/scripts/fetch_pricing_ostruct.py --model "$m" || true
          done

      - name: Merge pricing into data and normalize
        run: |
          poetry run python scripts/update_pricing.py
          poetry run python scripts/data_convert_unified_pricing.py

      - name: Validate pricing schema for cached files
        run: |
          poetry run python - <<'PY'
          import json, glob, sys
          from pathlib import Path
          import yaml
          try:
              import jsonschema
          except Exception:
              print('Installing jsonschema...')
              import subprocess
              subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'jsonschema'])
              import jsonschema
          schema = json.loads(Path('scripts/ostruct/pricing_schema.json').read_text())
          for p in glob.glob('pricing_data/*.yaml'):
              data = yaml.safe_load(open(p))
              jsonschema.validate(instance=data, schema=schema)
          print('schema OK')
          PY

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(pricing): merge ostruct pricing and normalize data"
          add: |
            pricing_data/*.yaml
            data/models.yaml
            data/overrides.yaml
          default_author: github_actions
          pull: false
