name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: "https://pypi.org/p/openai-model-registry"
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper version detection

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.8.3'
        virtualenvs-create: true

    - name: Show Poetry version
      run: poetry --version

    - name: Install dependencies
      run: poetry install

    - name: Run basic validation
      run: |
        poetry run python -c "import openai_model_registry; print('✅ Package imports successfully')"
        poetry check

    - name: Build package
      run: poetry build

    - name: Verify build
      run: |
        poetry run twine check dist/*
        ls -la dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No longer need PYPI_TOKEN - uses trusted publishing!
